name: "Feat (기능 추가)"
description: "새로운 기능을 추가할 때 사용합니다."
title: "[Feat] "
labels: ["Feat"]
type: Feature
body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "작업의 목적과 배경을 작성합니다."
      placeholder: "예: 사용자 편의를 위해 소셜 로그인 기능이 필요합니다."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "구체적인 작업 내용이나 상황을 작성합니다."
      placeholder: "예: 카카오 OAuth 2.0을 연동합니다."
  - type: textarea
    id: todo
    attributes:
      label: "To do"
      placeholder: "예: - [ ] 카카오 로그인 API 구현"
